### ISSUE TITLE
Removal of Ross-Ibarra_NSF_PlantGenome_2015.pdf

### ISSUE THREAD

**Issue by ethanwhite** [RILAB/statements#9]
@sdtaylor is implementing automated link checking for https://github.com/weecology/ogrants and it identified a broken link to Ross-Ibarra_NSF_PlantGenome_2015.pdf. It looks like it was here until August when it was removed as part of 5ff3f5edeb05838bdb7f36a5914850e768c08bf9. If you took it down on purpose that's totally fine, but wanted to check if it was accidental.

**Comment by ethanwhite** [comment]
Pinging this again after being reminded about it based on our twitter conversation earlier. I'm happy to just remove the grant from https://www.ogrants.org/, but didn't want to do so if this was unintentional.

**Comment by rossibarra** [comment]
Gah. Was unintentional. Will fix hopefully later today.

**Comment by ethanwhite** [comment]
Sound good. If it gets returned to the previous location the link should just start working again. If not we'll need to update the link. Thanks!
